### ISSUE TITLE
v2: top bar height affects bottom menu and scrolling bug

### ISSUE THREAD

**Issue by felixhahnweilheim** [cuzy-app/clean-theme#21]
- version 2 (beta)
- Set the top bar height to 100px

## 1. problem
The setting also affects the mobile bottom menu. This iformation should be added. Or it would be even better to have seperate settings.

## 2. problem
The top of the page is not visible on desktop.
The padding-top of `body` should get bigger (e.g. height of top bar + 20px).
![Screenshot 2024-07-12 at 10-36-44 weara - Felix Hahn Development](https://github.com/user-attachments/assets/86c6545c-b725-44b8-8b69-508db07a9b43)

## 3. problem
When scrolling on mobile, the top bar and bottom menu only disappear half.
![photo_2024-07-12_10-41-53](https://github.com/user-attachments/assets/6099761b-7c7f-4332-993a-5dc976917c7e)

**Comment by marc-farre** [comment]
@felixhahnweilheim Thank you very much for your detailed feedback.
Fixed in commit https://github.com/cuzy-app/clean-theme/commit/c3b2cba067dfb59050d1df81a6bc4dac468b504c
And released in version 2.0.0-beta.2 (available in the Marketplace)
