### ISSUE TITLE
v2: placement of export button on mobile

### ISSUE THREAD

**Issue by felixhahnweilheim** [cuzy-app/clean-theme#22]
Just a small placement issue.
The Export button on mobile looks a bit weird.

![photo_2024-07-12_10-48-20](https://github.com/user-attachments/assets/8c6692bd-2908-4b14-b562-42bce44eacfb)

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks!
Fixed in commit https://github.com/cuzy-app/clean-theme/commit/31ea2298913a44ec1a277e8779d910f4d6b88322
And released in version 2.0.0-beta.2 (available in the Marketplace)
