### ISSUE TITLE
On mobile, when scrolling down, the document can jump if its height is slightly higher than the screen

### ISSUE THREAD

**Issue by felixhahnweilheim** [cuzy-app/clean-theme#23]
Sometimes I have the bug that I can not scroll to the bottom, see Screenvideo.
The problem is I don't know exactly how to reproduce the error. It only happens sometimes.

https://github.com/user-attachments/assets/53837249-3a04-497c-84be-adaa9ea831f9

**Comment by felixhahnweilheim** [comment]
It has also happened on the global calendar page and other pages before. But as I said it is not really reproducible.
I am testing on Android 13, Samsung Galaxy A51

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks for reporting this issue. I've tested with different document height and I cannot reproduce.
Maybe if you find a page where it does it sometimes you can share the URL to me (in PM if you prefer)?
Thanks!

**Comment by marc-farre** [comment]
@felixhahnweilheim Can you test with the new 2.0.1 version? Thanks!

**Comment by felixhahnweilheim** [comment]
It still happens with v2.0.1

When the bottom (and top) menu appears, the content always jumps. I think it jumps exactly the height of the top bar.
Can you reproduce that?
I guess this is related.

The scroll bug always happens when a page is only a bit higher than the viewport.
And I guess the jumping is the problem.

**Comment by marc-farre** [comment]
@felixhahnweilheim I've just released version 2.0.2.
Can you test? Thank you very much!
